---
channel: edge
addons:
  nextcloud:
    repository: catadiel/nextcloud-addon
    target: nextcloud
    image: ghcr.io/catadiel/nextcloud/{arch}
  signal_messenger:
    repository: catadiel/signal-addon
    target: signal
    image: ghcr.io/catadiel/signal_messenger/{arch}
  jackett:
    repository: catadiel/jackett-addon
    target: jackett
    image: ghcr.io/catadiel/jackett/{arch}
  emby:
    repository: catadiel/emby-addon
    target: emby
    image: ghcr.io/catadiel/emby/{arch}
  transmission:
    repository: catadiel/hassio-addon-transmission
    target: transmission
    image: ghcr.io/catadiel/transmission/{arch}
